version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run: yarn run lint
      - run: yarn run test --ci
      - run: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - terraform
  deploy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.1.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform init & plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply
      - run:
          name: terraform apply
          command: |
            cd terraform
            terraform apply -auto-approve tfapply
workflows:
  version: 2
  deploy_to_prod:
    jobs:
      - build
      - deploy:
          requires:
            - build